name: win32_runner
description: >
  Compile and run a Flutter app without needing any C/C++ code. Just Dart!
version: 0.2.3
repository: https://github.com/halildurmus/win32_runner
issue_tracker: https://github.com/halildurmus/win32_runner/issues

topics:
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.5.0

platforms:
  windows:

dependencies:
  args: ^2.6.0
  ffi: ^2.1.3
  path: ^1.9.1
  win32: ^5.8.0
  win32_registry: ^2.0.0

dev_dependencies:
  hooks:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/hooks
  lints:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/lints
  test: ^1.25.8
