name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  semantic-pr:
    uses: halildurmus/workflows/.github/workflows/semantic_pr.yml@main

  spell-check:
    uses: halildurmus/workflows/.github/workflows/spell_check.yml@main
    with:
      includes: '**/*.md'
      modified_files_only: false
