name: win32_runner

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      analyze_directories: 'example lib test'

  dartdoc:
    uses: halildurmus/workflows/.github/workflows/dartdoc.yml@main

  pana:
    uses: halildurmus/workflows/.github/workflows/pana.yml@main
